---
include:
  - board: eyelash_corne_left
    shield: nice_view
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_studio_left
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
 
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: m165437 #new entry
      url-base: https://github.com/M165437 #new entry
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-gem #new entry
      remote: m165437 #new entry
      revision: main #new entry
  self:
    path: config
